image: maven:3.8-openjdk-11

stages:
  - build
  - lint
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
  MAVEN_CLI_OPTS:
    --batch-mode

cache:
  paths:
    - .m2/repository/

build-job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

lint-job:
  stage: lint
  script:
    - mvn checkstyle:checkstyle
  allow_failure: true

test-job:
  stage: test
  script:
    - mvn surefire-report:report -Dtest=PetStoreTest
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "**/target"
    reports:
      junit:
        - "**/target/*-reports/TEST-*.xml"